### ISSUE TITLE
ValidateHeader contract

### ISSUE THREAD

**Issue by younggentech** [central-university-dev/2023-autumn-ab-python-hw-14-team-dev-younggentech#17]
Currently, ValidateHeader class is raising an HTTPException with default fast api schema {"detail": ...}, but the documentation specifies another response contract for unsuccessful response {"success": False}. I consider this feature to be moderately important and suggest to fix it later, making it a tech debt.

**Comment by ilystsov** [comment]
As an option, we may define a custom exception.

**Comment by ilystsov** [comment]
After our discussion, we concluded that the current implementation aligns with the documentation. Therefore, we're closing this issue.

**Comment by ilystsov** [comment]
After our discussion, we concluded that the current implementation aligns with the documentation. Therefore, we're closing this issue.
